export default ar = {
    mobile: 'رقم الجوال',
    password: 'الرقم السرى',
    login: 'تسجيل الدخول',
    home: 'الرئيسية',
    offers: 'العروض',
    search: 'البحث',
    appointments: 'المواعيد',
    favourites: 'المفضلة',
    settings: 'الإعدادات',
    dontHaveAnAccount: 'لا تملك حساب ؟',
    signup: 'التسجيل',
    myInvoices: 'فواتيري',
    past: 'الفائتة',
    upcoming: 'القادمة',
    searchHome: 'البحث عن صالون التجميل',
    popularNear: 'قريبٌ منك',
    topOffer: 'أعلى العروض',
    filterSearch: 'تصفية البحث',
    selectArea: 'أين؟ اختر المنطقة',
    myCurrentLoc: 'موقعي الحالي',
    servicesCat: 'فئة الخدمات',
    servicesType: 'نوع الخدمات',
    priceRange: 'نطاق السعر',
    from: 'من',
    to: 'إلى',
    allSalons: 'كل الصالونات',
    onlySalonHaveOffer: ' فقط الصالونات التى لديها عروض',
    yourCurrentPoint: 'نقاطك الحالية',
    pointHistory: 'تاريخ النقاط',
    yourPoints: 'نقاطك',
    coupons: 'كوبونات',
    avCoupons: 'كوبونات متاحة',
    exCoupons: 'كوبونات منتهية',
    services: 'خدمات',
    about: 'عن الصالون',
    contact: 'تواصل معنا',
    contactInfo: 'معلومات التواصل',
    followUs: 'تابعنا على',
    imageGallery: 'معرض الصور',
    videoGallery: 'معرض المقاطع',
    location: 'موقع الصالون',
    facility: 'مرافق',
    notification: 'تنبيهات',
    editProfile: 'تعديل الملف الشخصي',
    offText: 'خصم',
    noInternetConnection: 'لا يوجد إتصال بالإنترنت',
    youAlreadyHaveAPackageAddedToTheAppointment: 'لديك بالفعل عرض مضاف إلى هذا الحجز',
    pleaseSelectTimesForAllServices: 'برجاء إختيار مواعيد لجميع الخدمات المختارة',
    youAlreadyHaveACouponAddedToThisAppointment: 'لديك بالفعل كوبون خصم مضاف إلى هذا الحجز',
    addNewAppointment: 'إضافة موعد جديد',
    areYouSure: 'هل أنت متأكد',
    ifYouChangedTheDayYouHaveToSelectNewTimesForAllServices: 'إذا قمت بتغيير اليوم يجب عليك إدخال أوقات لكل الخدمات المختارة',
    pleaseSelectTime: 'برجاء إختيار موعد',
    thisServiceIsAlreadyAdded: 'هذة الخدمة مضافة من قبل',
    thisServiceIsPartOfPackage: 'هذة الخدمة جزء من عرض',
    theWholePackageWillBeRemoved:'سيتم حذف العرض بأكمله',
    confirm: 'تأكيد',
    chooseDate: 'إختيار تاريخ الحجز',
    save: 'حفظ',
    cancel: 'إلغاء',
    yes: 'نعم',
    pleaseSelectDate: 'يرجي إختيار اليوم',
    selectStaffMember: 'إختر عضو الفريق',
    available: 'المتاح',
    selectClient: 'إختر العميل',
    addService: 'إضافة الخدمة',
    selectTime: 'إختر الوقت',
    addAnotherService: 'إضافة خدمة أخرى',
    noAvailableTimes: 'لا يوجد مواعيد متاحة',
    pleaseSelectTime: 'برجاء إختيار موعد',
    edit: 'تعديل',
    update: 'تحديث',
    preferredLanugage: 'اللغة المفضلة',
    english: 'English',
    arabic: 'العربية',
    yes: 'نعم',
    no: 'لا',
    packageDetails: 'تفاصيل الحزمة',
    bookNow: 'إحجز الأن',
    youAlreadySelectedThisTimeForAnotherService: 'لقد قمت بإختيار هذا الموعد لخدمة أخرى',
    confirmAppointment: 'تأكيد الحجز',
    noServices: 'لا يوجد خدمات',
    totalPriceBeforeTax: 'إجمالى المبلغ',
    totalTax: 'إجمالى الضريبة',
    discount: 'التخفيض',
    grandTotal: 'المبلغ الإجمالى',
    appointmentAddedSuccessfully: 'تم إضافة الموعد بنجاح',
    pleaseEnterACoupon: 'يرجي إدخال قسيمة خصم',
    changeDay: 'تغيير اليوم',
    noDataFound: 'لا يوجد بيانات متوفرة',
    creditCard: 'بطاقة ائتمان',
    drinks: 'مشروبات',
    wifi: 'واي فاي',
    delivery: 'خدمات منزلية',
    noImageFound: 'لم يتم العثور على صور',
    noVideoFound: 'لم يتم العثور على مقاطع فيديو',
    couponCode: 'كود الخصم',
    noOffersFound: 'لا يوجد عروض',
    RQ: '{0} ر.ق',
    loginWithYourMobile: 'تسجيل الدخول برقم الجوال',
    firstname: 'الإسم الأول',
    lastname: 'الإسم الأخير',
    passwordConfirmation: 'تأكيد الرقم السرى',
    email: 'البريد الإلكترونى',
    noAppointments: 'لا يوجد مواعيد',
    noInvoices: 'لا يوجد فواتير',
    noSaloons: 'لا توجد صالونات',
    username: 'إسم المستخدم',
    logout: 'تسجيل الخروج',
    completed: 'مكتمل',
    ourServices: 'خدماتنا',
    noFavSaloons: 'لا تمتلك صالونات مفضلة لديك',
    homeServices: 'خدمات منزلية',
    packages: 'الباقات',
    noPackages: 'لا توجد باقات متوفرة',
    hasOffers: 'يمتلك عروض',
    hasPackages: 'يمتلك باقات',
    openNow: 'مفتوح الان',
    area: 'منطقة',
    allArea: 'كل المناطق',
    selectService: 'اختار خدمة',
    date: 'تاريخ',
    selectDate: 'اختار تاريخ',
    saloonyDiscount: 'خصم صالوني',
    feedback: 'الشكاوي والمقترحات',
    noFeedbackFound: 'لا يوجد شكاوي ومقترحات',
    bookingNo: 'رقم الحجز: ',
    date: 'التاريخ: ',
    time: 'الوقت: ',
    price: 'التكلفة: ',
    address: 'العنوان: ',
    reload: 'إعادة التحميل',
    worker: 'الموظف:',
    servicePrice: 'تكلفة الخدمة: ',
    points: 'النقاط',
    totalBeforeTax: 'الإجمالى قبل الضريبة',
    forgotPasswordQues: 'نسيت كلمة المرور ؟',
    resetPassword: 'إسترجاع كلمة المرور',
    weJustNeedYourRegisteredMobileToSendResetLink: 'نحتاج فقط إلى رقم الجوال المسجل لإرسال رابط الإسترجاع',
    pricesFrom: 'الأسعار تبدأ من ',
    verificationCode: 'رمز التأكيد',
    iftheactivationcodeisnotreachedin: 'إذا لم يصلك رمز التفعيل خلال ',
    seconds: 'ثوانى',
    reSend: ' إعادة الإرسال',
    levelofservice: 'مستوى الخدمة ؟',
    levelofcleanliness: 'مستوى النظافة ؟',
    commitmenttothedeadline: 'الإلتزام بالمواعيد ؟',
    dealinginsidethesaloon: 'التعامل داخل الصالون ؟',
    pricelevel: 'مستوى الأسعار ؟',
    rate: 'تقييم',
    callUs: 'اتصل بنا',
    sendMessage: 'إذا كان لديك أي مشاكل يمكنك إرسال رسالة مباشرة إلى مدير التطبيق',
    send: 'إرسال',
    useCoupon: 'إستخدام القسيمة',
    couponCode: 'رمز القسيمة',
    getFreeService: 'إحصل على خدمة مجانية',
    currentPassword: 'الرقم السرى الحالى (مطلوب فى حالة تغيير الرقم السرى)',
    dateOfMarriage: 'تاريخ الزواج',
    dateOfBirth: 'تاريخ الميلاد',
    dateOfBirthOptional: 'تاريخ الميلاد (اختياري)',
    dateOfMarriageOptionl: 'تاريخ الزواج (اختياري)',
    profileUpdatedSuccessfully: 'تم تحديث الملف الشخصى بنجاح',
    subject: 'عنوان الشكوى',
    message: 'المحتوي',
    feedbackType: 'نوع التعليق',
    urgentComp: 'شكوى عاجلة',
    urgentOrd: 'شكوى عادية',
    complaints: 'شكاوي',
    enquiries: 'استفسارات',
    suggestions: 'اقتراحات',
    feedbackSendSuccess: 'تم إرسال ملاحظاتك بنجاح',
    contactUsSendSuccess: 'تم إرسال ملاحظاتك بنجاح',
    contactUs: 'اتصل بنا',
    noServicesMatchedWithThisCoupon: 'لا يوجد خدمات تناسب قسيمة الخصم',
    appointmentConfirmedAndPending: 'تم إرسال حجزك بنجاح وبإنتظار تأكيد مدير الصالون',
    ok: 'موافق',
    continueAsVisitor: 'أكمل كزائر',
    currentLang: 'اللغة الحالية :',
    lang: 'اللغة',
    active: 'مفعل',
    unActive: 'غير مفعل',
    pushNotifications: 'التنبيهات',
    emailOptional: 'البريد الإلكترونى (اختياري)',
    noPointHistory: 'لا يوجد تاريخ نقاط',
    delete: 'الغاء',
    confirmDelete: 'هل انت متأكد من الغاء هذا الحجز ؟',
    noteAppointment: 'سيتم إلغاء موعدك القادم بعد تأخير 15 دقيقة',
    completeAppointment: 'هناك حجز غير مكتمل بعد',
    complete: 'اكمل',
    youMustLogin: 'لابد من تسجيل الدخول لحجز الخدمات',
    registerNow: 'سجل الان للحصول على هذه الميزة واكثر !',
    giftCoupon: 'كوبونات الهدايا',
    addGiftedCoupons: 'اضافة كوبون هدايا',
    giftPrice: 'قمية القسيمة',
    giftDate: 'تاريخ ارسال القسيمة',
    giftChooseSaloon: 'اختار الصالون',
    sendToFriend: 'ارسال الى صديق',
    friendName: 'اسم الصديق',
    uploadBill: 'ارفاق صوره فاتورة الدفع',
    giftCouponNote: 'سيتم إرسال قسيمة الهدايا إلى صديقك في التاريخ المحدد بعد التحقق من التحويل المصرفي الخاص بك',
    clickToUpload: 'اضغط لارفاق صوره الفاتورة',
    uploading: 'تحميل الصور ...',
    needToUpload: ' (تحتاج الى رفع صوره الدفع)',
    convertToIpan: 'تم حفظ القسيمة الخاصة بك بنجاح! قم بتحويل قيمة القسيمة الى رقم الحساب هذا للتأكيد',
    afterUploadBill: 'تم تحميل الصورة بنجاح ، وسوف نتحقق من التحويل المصرفي ، ثم نرسل هديتك',


}