/* eslint-disable no-undef */
export default en = {
  mobile: 'Mobile number',
  password: 'Password',
  login: 'Login',
  home: 'Home',
  dontHaveAnAccount: 'Don\'t have an account ?',
  signup: 'Sign Up',
  myInvoices: 'My invoices',
  past: 'Past',
  upcoming: 'Upcoming',
  searchHome: 'Find the right beauty salon',
  popularNear: 'Popular Near You',
  topOffer: 'Top Offers',
  filterSearch: 'Search Filter',
  selectArea: 'Where? Select Area',
  myCurrentLoc: 'My Current Location',
  servicesCat: 'Services Category',
  servicesType: 'Services Type',
  priceRange: 'Price Range',
  from: 'From',
  to: 'To',
  allSalons: 'All Salons',
  onlySalonHaveOffer: 'Only Salons Have Offers',
  yourCurrentPoint: 'Your Current Points',
  pointHistory: 'Points History',
  yourPoints: 'Your Points',
  coupons: 'Coupons',
  avCoupons: 'Available Coupons',
  exCoupons: 'Expired Coupons',
  services: 'Services',
  about: 'About',
  contact: 'Contact',
  contactInfo: 'Contact Information',
  followUs: 'Follow us on',
  imageGallery: 'Image Gallery',
  videoGallery: 'Video Gallary',
  location: 'Location',
  facility: 'Facility',
  notification: 'Notification',
  editProfile: 'Edit profile',
  offText: 'Off',
  noInternetConnection: 'No internet connection',
  thisServiceIsPartOfPackage: 'This service is part of a package',
  theWholePackageWillBeRemoved: 'The whole package will be removed.',
  youAlreadyHaveAPackageAddedToTheAppointment: 'You already have a package added to this appointment',
  pleaseSelectTimesForAllServices: 'Please select times for all selected services',
  youAlreadyHaveACouponAddedToThisAppointment: 'You already have a Coupon added to this appointment',
  addNewAppointment: 'Add New Appointment',
  areYouSure: 'ARE YOU SURE',
  ifYouChangedTheDayYouHaveToSelectNewTimesForAllServices: 'If you changed the day you have to select new times for all selected services',
  pleaseSelectTime: 'Please select a time',
  thisServiceIsAlreadyAdded: 'This service is already added',
  confirm: 'Confirm',
  chooseDate: 'Choose appointment day',
  save: 'Save',
  cancel: 'Cancel',
  yes: 'Yes',
  pleaseSelectDate: 'Please select a day',
  selectStaffMember: 'Select Staff Member',
  available: 'Available',
  selectClient: 'Select client',
  addService: 'Add Service',
  selectTime: 'Select Time',
  addAnotherService: 'Add another service',
  noAvailableTimes: 'No available times',
  edit: 'Edit',
  update: 'Update',
  preferredLanugage: 'Preferred Lanugage',
  english: 'English',
  arabic: 'العربية',
  no: 'No',
  packageDetails: 'Package details',
  bookNow: 'Book now',
  youAlreadySelectedThisTimeForAnotherService: 'You already selected this time for another service',
  confirmAppointment: 'CONFIRM APPOINTMENT',
  noServices: 'No services',
  totalPriceBeforeTax: 'Total Price',
  totalTax: 'Total TAX',
  discount: 'Discount',
  grandTotal: 'Grand Total',
  appointmentAddedSuccessfully: 'Appointment added successfully',
  pleaseEnterACoupon: 'Please enter a coupon',
  changeDay: 'Change day',
  noDataFound: 'No Data Found',
  creditCard: 'Credit Card',
  drinks: 'Drinks',
  wifi: 'WIFI',
  delivery: 'Home Service',
  noImageFound: 'No images Found',
  noVideoFound: 'No Videos Found',
  couponCode: 'Coupon code',
  noOffersFound: 'No offers found',
  RQ: '{0} QR',
  loginWithYourMobile: 'Login with your mobile',
  firstname: 'First name',
  lastname: 'Last name',
  passwordConfirmation: 'Password confirmation',
  email: 'Email Address',
  noAppointments: 'No appointments',
  noInvoices: 'No invoices found',
  noSaloons: 'No saloon found',
  username: 'Username',
  logout: 'Logout',
  completed: 'Completed',
  ourServices: 'Our Services',
  noFavSaloons: 'You Don\'t Have Favourites Saloons',
  homeServices: 'Home Services',
  packages: 'Packages',
  noPackages: 'No Packages Found',
  hasOffers: 'Has Offers',
  hasPackages: 'Has Packages',
  openNow: 'Open Now',
  area: 'Area',
  allArea: 'All Areas',
  selectService: 'Select Service',
  date: 'Date',
  selectDate: 'Select Date',
  saloonyDiscount: 'Saloony discount',
  feedback: 'Feedback',
  noFeedbackFound: 'No feedback found',
  bookingNo: 'Booking No: ',
  time: 'Time: ',
  price: 'Price: ',
  address: 'Address: ',
  reload: 'Reload',
  worker: 'Worker:',
  servicePrice: 'Service price: ',
  points: 'Points',
  totalBeforeTax: 'Total before tax',
  forgotPasswordQues: 'Forgot Password !',
  resetPassword: 'Reset password',
  weJustNeedYourRegisteredMobileToSendResetLink: 'We just need your registered Mobile to send reset link',
  pricesFrom: 'Prices from ',
  verificationCode: 'Verification code',
  iftheactivationcodeisnotreachedin: 'If the activation code is not reached in ',
  seconds: 'Seconds',
  reSend: ' Resend',
  levelofservice: 'Level of service ?',
  levelofcleanliness: 'Level of cleanliness ?',
  commitmenttothedeadline: 'Commitment to the deadline ?',
  dealinginsidethesaloon: 'Dealing inside the saloon ?',
  pricelevel: 'Price level ?',
  rate: 'Rate',
  callUs: 'Call us',
  sendMessage: 'if you have any problems you can send a message directly to app manager',
  send: 'Send',
  useCoupon: 'Use coupon',
  getFreeService: 'Get free service',
  currentPassword: 'Current password(Required in case of changing your password)',
  dateOfMarriage: 'Date of marriage',
  dateOfBirth: 'Date of birth',
  dateOfBirthOptional: 'Date of birth (Optional)',
  dateOfMarriageOptionl: 'Date of marriage (Optional)',
  profileUpdatedSuccessfully: 'Profile updated successfully',
  subject: 'Subject',
  message: 'Message',
  feedbackType: 'Feedback Type',
  urgentComp: 'Urgent complaint',
  urgentOrd: 'Ordinary complaint',
  complaints: 'Complaints',
  enquiries: 'Enquiries',
  suggestions: 'Suggestions',
  feedbackSendSuccess: 'Your feedback sent successfully',
  contactUsSendSuccess: 'Your Message sent successfully',
  contactUs: 'Contact us',
  noServicesMatchedWithThisCoupon: 'No services matched with this coupon code',
  appointmentConfirmedAndPending: 'Your order has been submitted and is pending approval by an admin',
  ok: 'OK',
  continueAsVisitor: 'Continue as visitor',
  currentLang: 'Current Language :',
  lang: 'Language',
  active: 'Active',
  unActive: 'Not active',
  pushNotifications: 'Push Notifications',
  emailOptional: 'Email (Optional)',
  noPointHistory: 'No point history',
  delete: 'Delete',
  confirmDelete: 'Are you Sure ,you want to delete This Order',
  noteAppointment: 'Your upcoming appointmentwill be canceled after 15 min delay',
  completeAppointment: 'there is an appointment to be completed',
  complete: 'Complete',
  youMustLogin: 'You must login to appointment this service',
  registerNow: 'Register Now To access This feature and more !',
  giftCoupon: 'gift Coupons',
  addGiftedCoupons: 'Add Gift Coupon',
  giftPrice: 'Coupon Price',
  giftDate: 'Send Coupon Date',
  giftChooseSaloon: 'Choose Saloon',
  sendToFriend: 'Send to A friend',
  friendName: 'Friend Name',
  uploadBill: 'Upload Bill Photo',
  giftCouponNote: 'gift coupon will be sent to your friend in selected Date after checking your bank transfer',
  clickToUpload: 'Click to upload bill photo',
  uploading: 'Photo uploading ...',
  needToUpload: ' (you need to upload bill pic)',
  convertToIpan: 'your coupon saved successfully! transfer coupon price to this ipan',
  afterUploadBill: 'photo successfully uploaded we will check bank transfer then send your gift',
};
