import * as Expo from 'expo';
import { I18nManager } from 'react-native';

const locate = Expo.Localization.locale;

const Languages = {
  ar: {
    // commun
    search: 'بحث',
    // Root (Home)
    hotel: 'الفنادق',
    packages: 'صفقة',
    flight: 'رحلات',
    homes: 'منازل',
    transportation: 'وسائل النقل',
    book: 'إعادة البيع',
    assets: 'الأصول السوق',

    // Authentification Form
    passwordUp: 'كلمة المرور',
    passwordnor: 'كلمة المرور',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    loginSuccess: '',
    noAccount: 'لا تملك حساب؟',
    signup: 'تسجيل جديد',
    singupSuccess: '',
    Remembre: 'تذكرنى',
    haveAccount: 'ليس لديك حساب؟',
    email: 'البريد الالكتروني',
    enterEmail: 'أدخل البريد الالكتروني',
    enterPassword: 'أدخل الرقم السري ',
    name: 'الاسم',
    enterName: 'ادخل الاسم',
    confirmPassword: 'تأكيد كلمة المرور',
    // MenuSide
    wallet: 'محفظة',
    contact: 'إتصل بنا',
    aboutus: 'من نحن؟',
    setting: 'اعدادات',
    travel: 'السفر',
    terms: 'أحكام وشروط',
    privacy: 'سياسة خاصة',
    contactus: 'اتصل بنا',
    rateus: 'قيمنا',
    profile: 'الملف الشخصي',
    logout: 'تسجيل خروج ',

    // Hotels
    going: 'إلى أين ذاهب',
    ckeckin: 'الدخول',
    ckeckout: 'الخروج',
    guests: 'ضيوف',
    room: 'غرفة واحدة ، شخصان بالغان ، 0 طفل',

    // Flights
    OneWay: 'في إتجاه واحد',
    roundtrip: 'ذهاب وعودة',
    multiCity: 'مدن متعددة',
    from: 'من',
    to: 'إلى',
    departure: 'تاريخ المغادرة',
    return: 'تاريخ العودة',
    dirctflight: 'عرض الرحلة المباشرة فقط',
    flight1: 'الرحلة 1',
    flight2: 'الرحلة 2',
    flights: 'الرحلة',
    addFlight: 'أضف رحلة أخرى',
    // Layout
    cardView: 'Card View',
    simpleView: 'Simple View',
    twoColumnView: 'Two Column View',
    listView: 'List View',
    advanceView: 'Advance View',

    // readlater
    textBookMark: 'Bookmarks',
    textPosts: 'Posts',
    noBookmark: 'There is no bookmark item',
    ago: 'ago',
    allCategory: 'All Category',
    noResults: 'No Results',

    allTag: 'All Tag',
    user: 'User',

    discoverFashion: 'Discover\nLatest news',
    loginMsg: 'With more than 12M+ people discover\nthe fashion world',
    register: 'Register',
    emailAddress: 'Email Address',
    forgot: 'Forgot?',
    reset: 'Reset',
    signInWith: 'sign in with',
    dontHaveAnAccount: "Don't have an account?",
    username: 'Username',
    haveAnAccount: 'I have an account!',
    forYou: 'For you',
    msgForYou: 'Based on your reading history',
    popAuthor: 'Pop author',
    readingList: 'Reading list',
    featured: 'Featured',
    more: 'more',
    trending: 'Trending',
    follow: 'Follow',
    addComment: 'Add comment...',
    add: 'Add',
    cancel: 'Cancel',
    shareTheArtical: 'Share the article',
    ok: 'Ok',
    small: 'Small',
    normal: 'Normal',
    large: 'Large',
    comments: 'comments',
    notifications: 'Notifications',
    notificationsSubtitle: 'The history of all your activities',
    likes: 'Likes',
    follower: 'Follower',
    inbox: 'Inbox',
    popAuthorSubtitle: 'Hope to see on this page',
    today: 'Today',
    month: 'Month',
    allTime: 'All Time',
    readingListSubtitle: 'You can choose the label',
    fashion: 'Fashion',
    beauty: 'Beauty',
    culture: 'Culture',
    lifeLove: 'Life&Love',
    popularOnAmva: 'Popular on Amva',
    basedOnYourInterest: 'Based on your interest',
    fashionWeek: 'Fashion-week',
    luxurious: 'Luxurious',
    enterKeywords: 'Enter Keywords',
    searchHistory: 'Search history',
    peopleLikeThis: 'People like this',
    results: 'results',
    settings: 'Settings',
    rating: 'Rating',
    getHelp: 'Get help',
    about: 'About',
    dontMatchPassword: 'Password does not match the confirm password.',
    loginRequired: 'Login Required',
    loginRequiredMsg: 'You need to login to write comment.',
    share: 'Share',
    discover: 'Discover',
    publish: 'Publish',
    selectTheImage: 'Select the image',
    postHeading: 'Post heading',
    selectCategory: 'Select Category',
    allowAccessCameraroll: 'You need to turn on to allow access camera roll',
    next: 'Next',
    submit: 'Submit',
    composeTheContent: 'Compose the content...',
    errorMsgConnectServer: 'Can not connect to server.',
    successMsgPostNews: 'You submitted the post successfully.',
    readyToSubmit: 'Ready to submit?',
    notYet: 'Not yet',
    successfull: 'Successfull',
    close: 'Close',
    msgConfirmClearHistory: 'Are you sure you want to clear history?',
    confirmation: 'Confirmation',
    pickUp: ' Pick Up Date',
  },
  en: {
    // commun
    search: 'SEARCH',
    // Root (Home)
    hotel: 'HOTELS',
    packages: 'PACKAGES',
    flight: 'FLIGHTS',
    homes: ' HOMES',
    transportation: 'TRANSPORTATION',
    book: 'BOOK RE-SELLING',
    assets: 'ASSETS MARKETPLACE',

    // Athentification Form
    passwordUp: 'PASSWORD',
    passwordnor: 'password',
    forgotPassword: 'Forget password',
    for: 'Forgot Password',
    login: 'Sign In',
    loginSuccess: 'Sign In Successfull',
    noAccount: 'Do not have an account?',
    signup: 'Sign Up',
    signupSuccess: 'Sign Up Successfull',
    Remembre: 'Remember Me',
    haveAccount: 'Dont have an account?',
    email: 'EMAIL',
    enterEmail: 'Email Address',
    enterPassword: 'Type your password',
    confirmPassword: 'Confirm Password',
    name: 'NAME',
    enterName: 'Full name',
    // MenuSide
    wallet: 'WALLET',
    contact: 'Contact',
    travel: 'TRAVEL',
    profile: 'PROFILE',
    aboutus: 'ABOUT US',
    rateus: 'RATE US',
    contactus: 'CONTACT US',
    privacy: 'PRIVACY POLICY',
    terms: 'TERMS AND CONDITION',
    setting: 'Setting',
    logout: 'Logout',

    // Hotels
    going: 'where are you going',
    ckeckin: 'ckeck-in',
    ckeckout: 'ckeck-out',
    guests: 'guests',
    room: '1 Room,2 adult, 0 Children',

    // Flights
    OneWay: 'OneWay',
    roundtrip: 'Round Trip',
    multiCity: 'Multi-City',
    from: 'From',
    to: 'To',
    departure: ' Departure date',
    return: 'Return Date',
    dirctflight: 'Show Direct Flight Only',
    flight1: 'Flight 1',
    flight2: 'Flight 2',
    flights: 'Flight',
    addFlight: 'Add another flight',
    // Layout
    cardView: 'Card ',
    simpleView: 'List View',
    twoColumnView: 'Two Column ',
    threeColumnView: 'Three Column ',
    listView: 'List View',
    default: 'Default',
    advanceView: 'Advance ',
    mansoryView: 'Mansory View',
    horizontalView: 'Horizontal View',

    // readlater
    textBookMark: 'Bookmarks',
    textPosts: 'Posts',
    noBookmark: 'There is no bookmark item',
    ago: 'ago',
    allCategory: 'All Category',
    noResults: 'No Results',

    allTag: 'All Tags',
    user: 'User',

    discoverFashion: 'Discover\nLatest news',
    loginMsg: 'With more than 12M+ people discover\nthe fashion world',
    register: 'Register',
    emailAddress: 'Email Address',
    forgot: 'Forgot?',
    reset: 'Reset',
    signInWith: 'sign in with',
    dontHaveAnAccount: "Don't have an account?",
    username: 'Username',
    haveAnAccount: 'I have an account!',
    forYou: 'For you',
    msgForYou: 'Based on your reading history',
    popAuthor: 'Pop author',
    readingList: 'Reading list',
    featured: 'Featured',
    more: 'more',
    trending: 'Trending',
    follow: 'Follow',
    addComment: 'Add comment...',
    add: 'Add',
    cancel: 'Cancel',
    shareTheArtical: 'Share the article',
    ok: 'Ok',
    small: 'Small',
    normal: 'Normal',
    large: 'Large',
    comments: 'comments',
    notifications: 'Notifications',
    notificationsSubtitle: 'The history of all your activities',
    likes: 'Likes',
    follower: 'Follower',
    inbox: 'Inbox',
    popAuthorSubtitle: 'Hope to see on this page',
    today: 'Today',
    month: 'Month',
    allTime: 'All Time',
    readingListSubtitle: 'You can choose the label',
    fashion: 'Fashion',
    beauty: 'Beauty',
    culture: 'Culture',
    lifeLove: 'Life&Love',
    popularOnAmva: 'Popular on Amva',
    basedOnYourInterest: 'Based on your interest',
    fashionWeek: 'Fashion-week',
    luxurious: 'Luxurious',
    enterKeywords: 'Enter Keywords',
    searchHistory: 'Search history',
    peopleLikeThis: 'People like this',
    results: 'results',
    settings: 'Settings',
    rating: 'Rating',
    getHelp: 'Get help',
    about: 'About',
    dontMatchPassword: 'Password does not match the confirm password.',
    loginRequired: 'Login Required',
    loginRequiredMsg: 'You need to login to write comment.',
    share: 'Share',
    discover: 'Discover',
    publish: 'Publish',
    selectTheImage: 'Select the image',
    postHeading: 'Post heading',
    selectCategory: 'Select Category',
    allowAccessCameraroll: 'You need to turn on to allow access camera roll',
    next: 'Next',
    submit: 'Submit',
    composeTheContent: 'Compose the content...',
    errorMsgConnectServer: 'Can not connect to server.',
    successMsgPostNews: 'You submitted the post successfully.',
    readyToSubmit: 'Ready to submit?',
    notYet: 'Not yet',
    successfull: 'Successfull',
    close: 'Close',
    msgConfirmClearHistory: 'Are you sure you want to clear history?',
    confirmation: 'Confirmation',
    pickUp: ' Pick Up Date',
  },
};

// eslint-disable-next-line import/no-mutable-exports
let Language = Languages[locate];
if (I18nManager.isRTL) {
  Language = Languages.ar;
} else {
  Language = Languages.en;
}

export default Language;
